/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutIndex: typeof import('./src/components/about/AboutIndex.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElementPlus: typeof import('./src/components/utils/ElementPlus.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FileIndex: typeof import('./src/components/file/FileIndex.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeIndex: typeof import('./src/components/home/HomeIndex.vue')['default']
    ProcessIndex: typeof import('./src/components/process/ProcessIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptBlock: typeof import('./src/components/script/ScriptBlock.vue')['default']
    ScriptIndex: typeof import('./src/components/script/ScriptIndex.vue')['default']
    ScriptsContainer: typeof import('./src/components/script/ScriptsContainer.vue')['default']
    TerminalIndex: typeof import('./src/components/terminal/TerminalIndex.vue')['default']
    UtilityIndex: typeof import('./src/components/utility/UtilityIndex.vue')['default']
  }
}
