/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutIndex: typeof import('./components/about/AboutIndex.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElementPlus: typeof import('./components/utils/ElementPlus.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FileIndex: typeof import('./components/file/FileIndex.vue')['default']
    Greet: typeof import('./components/Greet.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomeIndex: typeof import('./components/home/HomeIndex.vue')['default']
    ProcessIndex: typeof import('./components/process/ProcessIndex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptIndex: typeof import('./components/script/ScriptIndex.vue')['default']
    ScriptsContainer: typeof import('./components/script/ScriptsContainer.vue')['default']
    TerminalIndex: typeof import('./components/terminal/TerminalIndex.vue')['default']
    UtilityIndex: typeof import('./components/utility/UtilityIndex.vue')['default']
  }
}
